# -*- coding: utf-8 -*-
"""square and cubes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bxmdQttGa4kIsAjF4qUyvxXoMqsRPhFj
"""

list1=[2,4,6,8,10]
square=[i**2 for i in list1]
print('square of numbers:',square)
cube=[i**3 for i in list1]
print('cube of numbers:',cube)

